import {chapters,outcomeLabels,allItems,itemTitle,classify,savedItems,relatedTo,exportMarkdown,mergeBackup,noteFor} from './knowledge.js?v=20261003-5';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>/^https?:\/\//i.test(String(v))?String(v):'#';
const link=(url,label)=>`<a class="source-link" href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;
const dateLabel=v=>v?String(v).replace(/^2026-/,'2026/').replace(/-(\d{2})$/,'/$1'):'';
const storageKey='aiworks-reading-room-feedback-v1';
const knowledgeId=url=>{let h=2166136261;for(const c of url)h=Math.imul(h^c.charCodeAt(0),16777619);return 'note-'+(h>>>0).toString(36)};
let content,feedback={items:{},generalNote:'',chapterNotes:{}},activeTab='x-posts',socialQuery='',knowledgeQuery='',knowledgeChapter='all',knowledgeOutcome='all',deepFilter='all',rejectUrl='',rejectTrigger;
let localToken='',localBase='',localTimer,pairWindow,localDocuments={},syncPending=false,syncAgain=false,pollTimer;
const historyView={'x-posts':false,podcasts:false,news:false,'deep-dives':false};
const topicLabels={case:'企業案例',product:'功能更新',trend:'觀點與趨勢',research:'研究報告'};
try{feedback={...feedback,...JSON.parse(localStorage.getItem(storageKey)||'{}')}}catch{}
feedback.items||={};feedback.chapterNotes||={};
const stateFor=url=>feedback.items[url]||{};
function saveLocalStorage(){try{localStorage.setItem(storageKey,JSON.stringify(feedback))}catch{document.getElementById('save-status').textContent='瀏覽器無法儲存筆記'}}
function save(){saveLocalStorage();clearTimeout(localTimer);localTimer=setTimeout(()=>localToken?syncLocal(true):sendInbox(),450)}
const tags=item=>`<span class="topic-tag">${esc(topicLabels[item.topic]||outcomeLabels[classify(item).outcome]||'觀點')}</span>${classify(item).concepts.slice(0,3).map(t=>`<span class="concept-tag">${esc(t)}</span>`).join('')}`;
function socialItems(){const items=[...(content.posts||[]),...(content.deepDives||[]).filter(x=>/https?:\/\/(www\.)?(x\.com|twitter\.com|linkedin\.com)\//.test(x.url)).map(x=>({...x,date:x.date||x.publishedAt?.slice(0,10)||x.sourceDate,highLevel:true,zh:x.lead,excerpt:x.originalExcerpt||'',author:x.author||x.source||'LinkedIn',topic:x.topic||'case'}))];return items.filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i)}
function dateMs(item){if(item.publishedAt)return Date.parse(item.publishedAt);if(/^\d{4}-\d{2}-\d{2}$/.test(item.date))return Date.parse(item.date+'T12:00:00+08:00');const m=(item.sourceDate||'').match(/(\d{4}) 年 (\d{1,2}) 月/);if(m)return Date.parse(`${m[1]}-${m[2].padStart(2,'0')}-01T00:00:00+08:00`);return 0}
function current(type,item){const age=(Date.now()-dateMs(item))/86400000;if(type==='podcasts')return true;const added=item.dailyBackfillAt?(Date.now()-Date.parse(item.dailyBackfillAt))/86400000:Infinity;if(added>=0&&added<14)return true;const rich=item.topic==='case'||item.retention==='six-months'||item.highLevel;return age>=-1&&age<(rich?184:14)}
function selected(type,items){return items.filter(x=>{const s=stateFor(x.url);return !s.saved&&(historyView[type]?s.read||s.rejected||!current(type,x):!s.read&&!s.rejected&&current(type,x))})}
function actions(item){const s=stateFor(item.url),url=esc(item.url);return `<div class="actions"><button data-action="read" data-url="${url}" class="action-button ${s.read?'is-active':''}" aria-pressed="${!!s.read}">✓ 已讀</button><button data-action="reject" data-url="${url}" class="action-button ${s.rejected?'is-active':''}" aria-pressed="${!!s.rejected}">${s.rejected?'↶ 取消沒幫助':'✕ 沒幫助'}</button><button data-action="save" data-url="${url}" class="action-button ${s.saved?'is-saved':''}" aria-pressed="${!!s.saved}">${s.saved?'★ 移回待讀':'☆ 收藏'}</button><details class="item-note"><summary>我的想法</summary><textarea data-note-url="${url}" aria-label="這篇的筆記">${esc(s.note||'')}</textarea></details>${s.rejectReason?`<details class="reject-note"><summary>略過理由</summary><p>${esc(s.rejectReason)}</p><button class="text-button" data-edit-reason="${url}">修改理由</button></details>`:''}</div>`}
function originalText(item){return item.originalExcerpt||item.excerpt||item.englishSummary||''}
function originalPane(item,{embed=false,media=''}={}){
 const text=originalText(item),x=/https?:\/\/(?:www\.)?(?:x|twitter)\.com\/[^/]+\/status\/\d+/.test(item.url);
 const body=embed&&x?`<div class="x-preview"><blockquote class="x-tweet-pending" data-conversation="none" data-dnt="true" lang="en"><p lang="en">${esc(text)}</p><a href="${esc(safeUrl(item.url))}">${esc(item.author||'X')} · ${esc(item.date||'')}</a></blockquote></div>`:`${media}${item.originalTitle?`<h3 lang="en">${esc(item.originalTitle)}</h3>`:''}${text?`<blockquote lang="${item.originalLanguage==='zh'?'zh-Hant':'en'}">${esc(text)}</blockquote>`:''}`;
 const kind=x?'X':/linkedin\.com/.test(item.url)?'LinkedIn':item.series||item.source||'原始資料';
 return `<div class="original-pane"><div class="pane-label">${esc(kind)}${item.englishSummary?' · English brief':item.originalIsFull?'':text?' · 原文節錄':''}</div>${body}${!text&&!media?'<p class="source-placeholder">'+esc(item.originalTitle||item.title||'')+'</p>':''}<div class="original-links">${link(item.url,'原文')}${item.evidenceUrl?link(item.evidenceUrl,item.evidenceLabel||'案例詳文'):''}</div></div>`;
}
function postCard(item){const detail=item.caseDetails?.length?`<details class="reading-detail"><summary>案例細節</summary><dl>${item.caseDetails.map(x=>`<div><dt>${esc(x.label)}</dt><dd>${esc(x.text)}</dd></div>`).join('')}</dl></details>`:'';const replies=item.replyObservation?`<details class="reading-detail"><summary>留言觀察 · ${item.replyObservation.count} 則</summary><p>${esc(item.replyObservation.summary)}</p><small>僅整理已核對的公開回覆。</small></details>`:'';return `<article class="post-card" id="social-${knowledgeId(item.url)}"><div class="card-meta"><span>${esc(item.author||item.source||'LinkedIn')} <span class="handle">${esc(item.handle||'')}</span></span><span>${esc(item.date||item.sourceDate||'')} ${tags(item)}</span></div><div class="reading-columns">${originalPane(item,{embed:true})}<div class="summary-pane"><h2>${esc(itemTitle(item))}</h2><p>${esc(item.zh||item.lead||'')}</p>${detail}${replies}${actions(item)}</div></div></article>`}
function podcastCard(item){const media=item.youtubeId?`<div class="podcast-media"><button class="video-trigger" data-video="${esc(item.youtubeId)}" data-video-title="${esc(item.title)}" aria-label="播放 ${esc(item.title)}"><img src="https://i.ytimg.com/vi/${esc(item.youtubeId)}/hqdefault.jpg" loading="lazy" alt=""><span>▶ 播放</span></button></div>`:item.cover?`<a class="podcast-art" href="${esc(safeUrl(item.url))}" target="_blank" rel="noopener noreferrer"><img src="${esc(item.cover)}" alt="${esc(item.series)}" loading="lazy"></a>`:'';return `<article class="podcast-card"><div class="card-meta"><span>${esc(item.series)}</span><span>${esc(item.date)} ${tags(item)}</span></div><div class="reading-columns">${originalPane(item,{media})}<div class="summary-pane"><h2>${esc(item.title)}</h2><p>${esc(item.context)}</p><ul>${(item.points||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${item.chapters?.length?`<details class="reading-detail"><summary>章節</summary><ul>${item.chapters.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`:''}${item.transcriptUrl?`<div class="transcript-access">${link(item.transcriptUrl,'英文逐字稿')}${item.altTranscriptUrl?link(item.altTranscriptUrl,'自動字幕'):''}<small>${esc(item.transcriptNote||'')}</small></div>`:''}${actions(item)}</div></div></article>`}
function newsCard(item){return `<article class="news-card"><div class="card-meta"><span>${esc(item.source)}</span><span>${esc(item.date||item.sourceDate)} ${item.dailyBackfillAt?'<span class="concept-tag">補讀</span>':''} ${tags(item)}</span></div><div class="reading-columns">${originalPane(item)}<div class="summary-pane"><h2>${esc(item.title)}</h2><p>${esc(item.what)}</p><ul>${(item.points||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${actions(item)}</div></div></article>`}
const categories={'x-posts':['posts-list','x-count',postCard],podcasts:['podcasts-list','podcast-count',podcastCard],news:['news-list','news-count',newsCard]};
function render(type){const [host,count,card]=categories[type];const pool=type==='x-posts'?socialItems():content[type]||[];let items=selected(type,[...pool].sort((a,b)=>dateMs(b)-dateMs(a)));document.getElementById(count).textContent=selected(type,pool).length;if(type==='x-posts'&&socialQuery)items=items.filter(x=>[itemTitle(x),x.zh,x.author,x.excerpt,...classify(x).concepts].join(' ').toLowerCase().includes(socialQuery.toLowerCase()));document.getElementById(host).innerHTML=items.length?items.map(card).join(''):'<div class="empty-state">沒有符合條件的內容。</div>';document.querySelector(`[data-view="${type}"]`).textContent=historyView[type]?'返回待讀':'已讀與歷史';if(type==='x-posts'){renderDigest();if(activeTab===type)loadXEmbeds()}}
let embedScriptLoaded=false,xObserver;const observedTweets=new WeakSet();
function observeX(){if(!window.twttr?.widgets?.load)return;xObserver||=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const quote=e.target;quote.classList.replace('x-tweet-pending','twitter-tweet');window.twttr.widgets.load(quote.parentElement);xObserver.unobserve(quote)}),{rootMargin:'350px'});document.querySelectorAll('#posts-list .x-tweet-pending').forEach(node=>{if(!observedTweets.has(node)){observedTweets.add(node);xObserver.observe(node)}})}
function loadXEmbeds(){if(!document.querySelector('#posts-list .x-tweet-pending'))return;if(window.twttr?.widgets?.load){observeX();return}if(embedScriptLoaded)return;embedScriptLoaded=true;const script=document.createElement('script');script.src='https://platform.twitter.com/widgets.js';script.async=true;script.onload=observeX;document.head.append(script)}
function renderDigest(){const base=Date.now(),items=socialItems().filter(x=>{const s=stateFor(x.url),ts=x.publishedAt?Date.parse(x.publishedAt):0;return ts&&base-ts>=0&&base-ts<=86400000&&!s.saved&&!s.read&&!s.rejected});const d=content.digest;const checked=d?.checkedAt?new Date(d.checkedAt):null;const valid=checked&&base-checked.getTime()<86400000;document.getElementById('daily-digest').innerHTML=`<div class="digest-heading"><h2>過去 24 小時</h2><time>${valid?new Intl.DateTimeFormat('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Taipei'}).format(checked)+' 更新':''}</time></div>${valid&&d.points?.length?`<ul>${d.points.map(p=>`<li>${esc(p.text)} ${p.url?`<button class="inline-link" data-source-jump="${esc(p.url)}">${esc(p.label||'查看貼文')}</button>`:''}</li>`).join('')}</ul>`:items.length?`<ul>${items.slice(0,4).map(x=>`<li><button class="inline-link" data-source-jump="${esc(x.url)}">${esc(itemTitle(x))}</button> <span>${esc(x.zh||'')}</span></li>`).join('')}</ul>`:`<p class="digest-empty">${valid?esc(d.emptyMessage||'這次未找到符合條件的新貼文。'):'目前沒有已核對的 24 小時摘要。'}</p>`}`}
function deepCard(item){return `<article class="deep-card" id="deep-${knowledgeId(item.url)}"><div class="card-meta"><span>${esc(item.type||item.source||'')}</span><time>${esc(item.sourceDate||item.date||'')}</time></div><div class="reading-columns">${originalPane(item)}<div class="summary-pane"><h2>${esc(item.title)}</h2><p>${esc(item.lead||item.what||item.context||item.zh||'')}</p>${(item.takeaways||item.points)?.length?`<ul>${(item.takeaways||item.points).map(p=>`<li>${esc(p)}</li>`).join('')}</ul>`:''}${item.caveat?`<p class="evidence-limit">${esc(item.caveat)}</p>`:''}${item.sources?`<div>${item.sources.map(s=>link(s.url,s.label)).join('')}</div>`:''}${actions(item)}</div></div></article>`}
function renderDeep(){const all=allItems(content);const sets=(content.readingSets||[]).filter(set=>deepFilter==='all'||set.urls.some(u=>{const item=all.find(x=>x.url===u);return item&&classify(item).outcome===deepFilter}));document.getElementById('deep-count').textContent=sets.length;document.querySelector('[data-view="deep-dives"]').hidden=true;document.querySelectorAll('[data-deep-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.deepFilter===deepFilter)));document.getElementById('deep-list').innerHTML=sets.map(set=>{const sources=set.urls.map(u=>all.find(x=>x.url===u)).filter(Boolean);return `<section class="reading-set"><h2>${esc(set.title)}</h2><p class="set-context">${esc(set.summary)}</p>${sources.map(x=>`<div class="set-source"><span>${esc(x.date||x.sourceDate||'')}${stateFor(x.url).saved?' · 收藏筆記':''}</span><button class="inline-link" data-source-jump="${esc(x.url)}">${esc(itemTitle(x))}</button><p>${esc(noteFor(x).summary)}</p></div>`).join('')}</section>`}).join('')||'<div class="empty-state">目前沒有符合條件的主題。</div>'}
function renderAll(){Object.keys(categories).forEach(render);renderDeep();renderKnowledge();renderFeedback()}
function activateTab(type,focus=false){if(!categories[type]&&!['deep-dives','knowledge'].includes(type))type='x-posts';activeTab=type;document.querySelectorAll('.tabs button').forEach(t=>{const on=t.dataset.tab===type;t.setAttribute('aria-pressed',String(on));if(on&&focus)t.focus()});document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==type);if(type==='x-posts')loadXEmbeds();if(type==='knowledge')renderKnowledge();if(location.hash!==`#view-${type}`)history.replaceState(null,'',`#view-${type}`)}
function updateItem(url,action,reason){const s=feedback.items[url]||={};if(action==='read'){s.read=!s.read;if(s.read)s.rejected=false}if(action==='reject'){if(!s.rejected&&!reason?.trim())return false;s.rejected=!s.rejected;if(s.rejected){s.rejectReason=reason.trim();s.read=false}}if(action==='reason'){if(!reason?.trim())return false;s.rejectReason=reason.trim()}if(action==='save'){s.saved=!s.saved;if(!s.saved){s.read=false;s.rejected=false}else{s.savedAt=new Date().toISOString();s.snapshot=allItems(content).find(x=>x.url===url)||s.snapshot;s.enrichmentStatus||='pending'}document.getElementById('reading-status').innerHTML=s.saved?'<button class="text-button" data-open-knowledge>已收藏 →</button>':'已移回待讀'}s.updatedAt=new Date().toISOString();save();renderAll();return true}
function openReject(url,trigger){rejectUrl=url;rejectTrigger=trigger;document.getElementById('reject-reason').value=stateFor(url).rejectReason||'';document.getElementById('reject-error').textContent='';document.getElementById('reject-dialog').showModal();document.getElementById('reject-reason').focus()}
function openKnowledgeItem(url){knowledgeChapter='all';knowledgeQuery='';knowledgeOutcome='all';document.getElementById('knowledge-search').value='';document.getElementById('knowledge-outcome').value='all';activateTab('knowledge');requestAnimationFrame(()=>document.getElementById(knowledgeId(url))?.scrollIntoView({block:'start',behavior:'auto'}))}
function openSource(url){if(stateFor(url).saved){openKnowledgeItem(url);return}let type,target;if(socialItems().some(x=>x.url===url)){type='x-posts';socialQuery='';document.getElementById('social-search').value='';historyView[type]=!current(type,socialItems().find(x=>x.url===url))||!!(stateFor(url).read||stateFor(url).rejected);render(type);target='social-'+knowledgeId(url)}else{const item=allItems(content).find(x=>x.url===url);if(!item)return;type=item.kind;historyView[type]=!current(type,item)||!!(stateFor(url).read||stateFor(url).rejected);render(type)}activateTab(type);requestAnimationFrame(()=>{const node=target?document.getElementById(target):[...document.querySelectorAll(`#${type} article`)].find(x=>x.querySelector('[data-url]')?.dataset.url===url);node?.scrollIntoView({block:'start',behavior:'auto'})})}
function markdown(text){
 const cleaned=String(text).replace(/<!--[\s\S]*?-->/g,'');
 const inline=value=>esc(value).replace(/\[([^\]]+)\]\(([^)]+)\)/g,(match,label,url)=>{let source=null;try{source=url.startsWith('note:')?decodeURIComponent(url.slice(5)):Object.entries(localDocuments).find(([,d])=>url.replace(/^\.\//,'')===d.file)?.[0]||allItems(content).find(x=>url.replace(/^\.\//,'')===knowledgeId(x.url)+'.md')?.url}catch{};return source?`<button class="inline-link" data-related="${esc(source)}">${label}</button>`:/^https?:\/\//.test(url)?`<a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`:match}).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
 return cleaned.split(/\n\s*\n/).filter(p=>p.trim()).map(p=>{const lines=p.trim().split('\n');if(/^#{1,4} /.test(lines[0]))return `<h4>${inline(lines[0].replace(/^#{1,4} /,''))}</h4>`+(lines.length>1?markdown(lines.slice(1).join('\n')):'');if(lines.every(l=>/^- /.test(l)))return '<ul>'+lines.map(l=>`<li>${inline(l.slice(2))}</li>`).join('')+'</ul>';return '<p>'+lines.map(inline).join('<br>')+'</p>'}).join('');
}
function noteBodyMarkup(body){const parts=body.split(/^## 中文筆記\s*$/m);if(parts.length===2&&/^(## English|## 英文)/m.test(parts[0]))return markdown(parts[0])+'<details class="knowledge-chinese"><summary>中文筆記</summary>'+markdown(parts[1])+'</details>';return markdown(body)}
function connectionParagraphs(item,all){const explicit=relatedTo(item,all).filter(r=>r.score>=20);return explicit.slice(0,2).map(r=>`<p>${esc(r.reason.replace(/[。.!]+$/,''))}。可對照 <button class="inline-link" data-related="${esc(r.item.url)}">${esc(itemTitle(r.item))}</button> 的筆記：${esc(r.item.note.summary)}</p>`).join('')}
function knowledgeCard(item,all){const doc=localDocuments[item.url],en=item.knowledge?.englishNote||item.englishSummary||originalText(item),body=doc?.body||item.knowledge?.noteBody||'';return `<article id="${knowledgeId(item.url)}" class="knowledge-card" tabindex="-1"><div class="knowledge-meta"><span>${esc(outcomeLabels[item.info.outcome])}</span><span>${esc(item.date||item.sourceDate||'')}</span></div><h3>${esc(itemTitle(item))}</h3>${body?`<div class="note-body">${noteBodyMarkup(body)}</div>`:`${en?`<div class="knowledge-english" lang="en">${markdown(en)}</div>`:''}<details class="knowledge-chinese" ${en?'':'open'}><summary>中文筆記</summary><p>${esc(item.note.summary)}</p>${item.note.points.length?`<ul>${item.note.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul>`:''}${item.note.limit?`<p class="evidence-limit">${esc(item.note.limit)}</p>`:''}</details>${connectionParagraphs(item,all)?`<div class="note-connections">${connectionParagraphs(item,all)}</div>`:''}`}<div class="knowledge-sources">${item.note.sources.map(s=>link(s.url,s.label)).join('')}</div><div class="knowledge-taxonomy"><label>章節 <select data-reclassify="${esc(item.url)}" aria-label="調整章節">${chapters.map(c=>`<option value="${c.id}" ${c.id===item.info.primary?'selected':''}>${esc(c.title)}</option>`).join('')}</select></label>${item.info.concepts.map(c=>`<span>${esc(c)}</span>`).join('')}${doc?`<a href="${esc(localBase)}/api/note/${esc(knowledgeId(item.url))}?download=1" class="text-button" data-download-note="${esc(item.url)}">Markdown ↗</a>`:item.knowledge?.markdownFile?`<a href="./${esc(item.knowledge.markdownFile)}" class="text-button" target="_blank" rel="noopener">Markdown ↗</a>`:''}</div>${actions(item)}</article>`}
function renderKnowledge(){const opened=new Set([...document.querySelectorAll('#knowledge-list details[open]')].map(d=>(d.closest('.knowledge-card')?.id||d.closest('.knowledge-chapter')?.querySelector('h2')?.textContent)+'|'+d.querySelector('summary')?.textContent));const all=savedItems(content,feedback);document.getElementById('knowledge-count').textContent=all.length;const counts=Object.fromEntries(chapters.map(c=>[c.id,all.filter(x=>x.info.primary===c.id).length]));document.getElementById('knowledge-nav').innerHTML='<button data-chapter="all" aria-pressed="'+(knowledgeChapter==='all')+'">全部</button>'+chapters.filter(c=>counts[c.id]||feedback.chapterNotes[c.id]).map(c=>`<button data-chapter="${c.id}" aria-pressed="${knowledgeChapter===c.id}">${esc(c.title)}</button>`).join('');const q=knowledgeQuery.trim().toLowerCase();const items=all.filter(x=>(knowledgeChapter==='all'||x.info.primary===knowledgeChapter)&&(knowledgeOutcome==='all'||x.info.outcome===knowledgeOutcome)&&(!q||[itemTitle(x),x.note.summary,...x.note.points,x.state.note,...x.info.concepts,localDocuments[x.url]?.body].join(' ').toLowerCase().includes(q)));document.getElementById('knowledge-list').innerHTML=chapters.filter(c=>items.some(x=>x.info.primary===c.id)||knowledgeChapter===c.id&&feedback.chapterNotes[c.id]).map(c=>`<section class="knowledge-chapter"><h2>${esc(c.title)}</h2><details class="chapter-notes"><summary>章節筆記</summary><textarea data-chapter-note="${c.id}" aria-label="章節筆記">${esc(feedback.chapterNotes[c.id]||'')}</textarea></details>${items.filter(x=>x.info.primary===c.id).map(x=>knowledgeCard(x,all)).join('')}</section>`).join('')||'<div class="empty-state">沒有符合條件的筆記。</div>';document.querySelectorAll('#knowledge-list details').forEach(d=>{const key=(d.closest('.knowledge-card')?.id||d.closest('.knowledge-chapter')?.querySelector('h2')?.textContent)+'|'+d.querySelector('summary')?.textContent;if(opened.has(key))d.open=true})}
function renderFeedback(){document.getElementById('feedback-list').innerHTML=Object.entries(feedback.items).filter(([,s])=>s.read||s.rejected||s.saved||s.note).map(([url,s])=>`<div class="feedback-item"><strong>${esc(itemTitle(allItems(content).find(x=>x.url===url)||s.snapshot||{url,title:url}))}</strong><span>${[s.read?'已讀':'',s.rejected?'沒幫助':'',s.saved?'收藏':''].filter(Boolean).join(' · ')}</span>${s.rejectReason?`<p>理由：${esc(s.rejectReason)}</p>`:''}${s.note?`<p>${esc(s.note)}</p>`:''}</div>`).join('')}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function localRequest(path,body){const r=await fetch(localBase+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+localToken,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function syncLocal(write=false){if(!localToken)return;if(syncPending){if(write)syncAgain=true;return}syncPending=true;try{const response=await localRequest('/api/library',write?feedback:undefined);const active=document.activeElement;if(!active?.matches('textarea,input,select')){const before=JSON.stringify(feedback);feedback=mergeBackup(feedback,response.feedback);feedback.chapterNotes={...feedback.chapterNotes,...response.feedback.chapterNotes};feedback.generalNote=response.feedback.generalNote??feedback.generalNote;document.getElementById('reading-notes').value=feedback.generalNote;const changed=before!==JSON.stringify(feedback);const docsChanged=JSON.stringify(localDocuments)!==JSON.stringify(response.documents);localDocuments=response.documents;saveLocalStorage();if(changed)renderAll();else if(docsChanged)renderKnowledge()}else localDocuments=response.documents;document.getElementById('local-status').textContent='本機已連結';document.getElementById('refresh-local').hidden=false;document.getElementById('connect-local').textContent='本機版'}catch{document.getElementById('local-status').textContent='本機暫時未連線'}finally{syncPending=false;if(syncAgain){syncAgain=false;syncLocal(true)}}}
async function sendInbox(){if(location.hostname!=='aa0979090122-coder.github.io')return false;try{const r=await fetch('http://127.0.0.1:8766/api/inbox',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(3000),body:JSON.stringify(feedback)});if(!r.ok)throw Error();document.getElementById('local-status').textContent='收藏已存到本機';return true}catch{document.getElementById('local-status').textContent='收藏已存於瀏覽器';return false}}
async function connectLocal(){if(localToken){await syncLocal();activateTab('knowledge');return}if(await sendInbox())location.href='http://127.0.0.1:8766/#view-knowledge';else document.getElementById('local-status').innerHTML='<a href="http://127.0.0.1:8766/" target="_blank" rel="noopener">開啟本機版 ↗</a>'}
async function initLocal(){if(['127.0.0.1','localhost'].includes(location.hostname)){try{const r=await fetch('/api/bootstrap',{cache:'no-store'});if(!r.ok)return;const data=await r.json();localBase=location.origin;localToken=data.token;await syncLocal(true);pollTimer=setInterval(()=>syncLocal(),5000)}catch{}}else await sendInbox()}
async function init(){try{const r=await fetch('./content.json?v=20261003-5',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);content=await r.json();for(const note of content.knowledgeLibrary||[]){if(!feedback.items[note.url])feedback.items[note.url]={saved:true,chapter:note.chapter,savedAt:note.savedAt}}for(const item of allItems(content)){const s=stateFor(item.url);if(s.saved&&!s.snapshot)s.snapshot=item}document.getElementById('edition-date').textContent='更新 '+dateLabel(content.editionDate);document.getElementById('reading-notes').value=feedback.generalNote||'';
 document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{activateTab(b.dataset.tab);window.scrollTo(0,0)}));document.querySelector('.tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const keys=['x-posts','podcasts','news','deep-dives','knowledge'];activateTab(keys[(keys.indexOf(activeTab)+(e.key==='ArrowRight'?1:-1)+keys.length)%keys.length],true)});
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{historyView[b.dataset.view]=!historyView[b.dataset.view];b.dataset.view==='deep-dives'?renderDeep():render(b.dataset.view)}));
 document.querySelector('.content').addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-reason]');if(edit){openReject(edit.dataset.editReason,edit);return}const a=e.target.closest('[data-action]');if(a){if(a.dataset.action==='reject'&&!stateFor(a.dataset.url).rejected)openReject(a.dataset.url,a);else updateItem(a.dataset.url,a.dataset.action);return}const v=e.target.closest('[data-video]');if(v){v.closest('.podcast-media').innerHTML=`<iframe class="podcast-video" src="https://www.youtube-nocookie.com/embed/${esc(v.dataset.video)}?autoplay=1" title="${esc(v.dataset.videoTitle)}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;return}const d=e.target.closest('[data-deep-filter]');if(d){deepFilter=d.dataset.deepFilter;renderDeep();return}const j=e.target.closest('[data-related]');if(j){openSource(j.dataset.related);return}const sj=e.target.closest('[data-source-jump]');if(sj){openSource(sj.dataset.sourceJump);return}const c=e.target.closest('[data-chapter]');if(c){knowledgeChapter=c.dataset.chapter;renderKnowledge();return}const dn=e.target.closest('[data-download-note]');if(dn){e.preventDefault();const doc=localDocuments[dn.dataset.downloadNote];if(doc)download(knowledgeId(dn.dataset.downloadNote)+'.md',doc.markdown,'text/markdown;charset=utf-8')}});
 document.querySelector('.content').addEventListener('input',e=>{if(e.target.matches('[data-note-url]')){const s=feedback.items[e.target.dataset.noteUrl]||={};s.note=e.target.value;s.updatedAt=new Date().toISOString();save();renderFeedback()}if(e.target.matches('[data-chapter-note]')){feedback.chapterNotes[e.target.dataset.chapterNote]=e.target.value;feedback.chapterNotesUpdatedAt||={};feedback.chapterNotesUpdatedAt[e.target.dataset.chapterNote]=new Date().toISOString();save()}});
 document.getElementById('reject-form').addEventListener('submit',e=>{e.preventDefault();const reason=document.getElementById('reject-reason').value.trim();if(!reason){document.getElementById('reject-error').textContent='請寫下理由';return}const action=stateFor(rejectUrl).rejected?'reason':'reject';if(updateItem(rejectUrl,action,reason))document.getElementById('reject-dialog').close()});document.getElementById('cancel-reject').addEventListener('click',()=>document.getElementById('reject-dialog').close());document.getElementById('reject-dialog').addEventListener('close',()=>{if(rejectTrigger?.isConnected)rejectTrigger.focus()});
 document.getElementById('social-search').addEventListener('input',e=>{socialQuery=e.target.value;render('x-posts')});document.getElementById('knowledge-search').addEventListener('input',e=>{knowledgeQuery=e.target.value;renderKnowledge()});document.getElementById('knowledge-outcome').addEventListener('change',e=>{knowledgeOutcome=e.target.value;renderKnowledge()});document.getElementById('knowledge-list').addEventListener('change',e=>{if(e.target.matches('[data-reclassify]')){const s=feedback.items[e.target.dataset.reclassify];s.chapter=e.target.value;s.updatedAt=new Date().toISOString();save();renderKnowledge()}});
 document.getElementById('reading-notes').addEventListener('input',e=>{feedback.generalNote=e.target.value;feedback.generalNoteUpdatedAt=new Date().toISOString();save()});document.getElementById('copy-feedback').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(JSON.stringify(feedback,null,2));document.getElementById('save-status').textContent='已複製'}catch{document.getElementById('save-status').textContent='未能複製'}});document.getElementById('reading-status').addEventListener('click',e=>{if(e.target.closest('[data-open-knowledge]'))activateTab('knowledge')});document.getElementById('export-notes').addEventListener('click',()=>download('knowledge.md',exportMarkdown(content,feedback,localDocuments),'text/markdown;charset=utf-8'));document.getElementById('export-backup').addEventListener('click',()=>download('reading-backup.json',JSON.stringify({version:3,...feedback},null,2),'application/json'));document.getElementById('import-backup').addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;feedback=mergeBackup(feedback,JSON.parse(await f.text()));save();renderAll();document.getElementById('knowledge-status').textContent='已合併'}catch{document.getElementById('knowledge-status').textContent='無法匯入'}e.target.value=''});
 document.getElementById('connect-local').addEventListener('click',connectLocal);document.getElementById('refresh-local').addEventListener('click',()=>syncLocal()); window.addEventListener('storage',e=>{if(e.key===storageKey&&e.newValue){try{feedback={...feedback,...JSON.parse(e.newValue)};renderAll()}catch{}}});window.addEventListener('hashchange',()=>activateTab(location.hash.slice(1).replace(/^view-/,'')));saveLocalStorage();renderAll();activateTab(location.hash.slice(1).replace(/^view-/,''));await initLocal();
 }catch(e){console.error(e);document.getElementById('posts-list').innerHTML='<p class="empty-state">內容載入失敗，請重新整理。</p>'}}
init();
