import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const code=await readFile(new URL('../knowledge.js',import.meta.url),'utf8');
const {savedItems,relatedTo,mergeBackup,exportMarkdown}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const content=JSON.parse(await readFile(new URL('../content.json',import.meta.url),'utf8'));
const a=content.deepDives.find(x=>x.url.includes('fine-tuning-agent'));
const b=content.deepDives.find(x=>x.url.includes('continual-learning'));
const oldUrl='https://example.org/preserved';
const feedback={items:{[a.url]:{saved:true,note:'保留我的觀點',updatedAt:'2026-10-02T01:00:00Z'},[b.url]:{saved:true},[oldUrl]:{saved:true,snapshot:{url:oldUrl,title:'歷史收藏',zh:'保留來源'},note:'歷史筆記'}},chapterNotes:{evaluation:'我的綜合判斷'}};
const saved=savedItems(content,feedback);
assert.equal(saved.length,3);
assert.equal(saved.find(x=>x.url===a.url).info.primary,'evaluation');
assert.equal(saved.find(x=>x.url===oldUrl).title,'歷史收藏');
assert(relatedTo(saved.find(x=>x.url===a.url),saved).some(r=>r.item.url===b.url&&r.reason.includes('失敗復盤')));
assert(relatedTo(saved.find(x=>x.url===b.url),saved).some(r=>r.item.url===a.url));
const merged=mergeBackup(feedback,{items:{[a.url]:{note:'舊備份',updatedAt:'2025-01-01'},'https://new.example':{saved:true,note:'新資料'}}});
assert.equal(merged.items[a.url].note,'保留我的觀點');
assert.equal(merged.items[oldUrl].note,'歷史筆記');
assert(merged.items['https://new.example'].saved);
const md=exportMarkdown(content,feedback);
assert(md.includes('我的綜合判斷')&&md.includes(a.url)&&md.includes(b.url)&&md.includes('保留我的觀點'));
feedback.items[a.url].chapter='workflow';
assert.equal(savedItems(content,feedback).find(x=>x.url===a.url).info.primary,'workflow');
feedback.items[a.url].saved=false;
assert(!savedItems(content,feedback).some(x=>x.url===a.url));
assert.equal(feedback.items[a.url].note,'保留我的觀點');
console.log('Passed: existing favorites, preserved sources, two-way links, classification override, additive restore, export, unsave.');
